#version: "3.8"

#services:
#  backend:
#   build: 
#      context: ./backend
#    ports:
#      - "${PORT_BACKEND}:${PORT_BACKEND}"
#    environment:
#      - MONGO_URI=mongodb://host.docker.internal:${PORT_MONGO}/${MONGO_DBNAME}
#      - JWT_SECRET=${JWT_SECRET}
#      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

#  frontend:
#    build:
#      context: ./my-react-app
#    ports:
#      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
#    depends_on:
#      - backend
version: "3.8"

services:


  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:${PORT_MONGO}/${MONGO_DBNAME}
      - JWT_SECRET=your_jwt_secret

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80" # Map container port 80 (Nginx) to localhost:3000
    depends_on:
      - backend
